services:
  node-app:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "8000:80"
