version: '3'
services:
  node-app:
    build: ./node
    ports:
      - "3000:3000"

  php-app:
    build: ./php
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: super-app
    ports:
      - "3306:3306"